# Generated by Django 3.2.4 on 2021-06-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('user_gender', models.CharField(max_length=6)),
                ('user_age', models.IntegerField(max_length=2)),
                ('user_education', models.CharField(max_length=200)),
                ('user_frequency', models.CharField(max_length=200)),
                ('user_genre', models.CharField(max_length=200)),
                ('user_race', models.CharField(max_length=200)),
                ('test_type', models.IntegerField(max_length=1)),
                ('user_entry_time', models.TimeField(max_length=200)),
                ('time_spent', models.DurationField(max_length=200)),
                ('feedback_rate', models.IntegerField(max_length=1)),
                ('feedback_satisfied', models.IntegerField(max_length=1)),
                ('feedback_likely', models.IntegerField(max_length=1)),
                ('feedback_relay', models.IntegerField(max_length=1)),
                ('feedback_think', models.IntegerField(max_length=1)),
                ('feedback_study', models.IntegerField(max_length=1)),
                ('movie_link_clicked', models.IntegerField(max_length=1)),
            ],
        ),
    ]
