# Generated by Django 3.2.4 on 2021-06-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='feedback_likely',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='feedback_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='feedback_relay',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='feedback_satisfied',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='feedback_study',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='feedback_think',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='movie_link_clicked',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='test_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_age',
            field=models.IntegerField(),
        ),
    ]
