# Generated by Django 3.2.4 on 2021-06-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210618_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_spent',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_entry_time',
            field=models.CharField(max_length=200),
        ),
    ]
