# Generated by Django 3.2.4 on 2021-06-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20210618_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='feedback_likely',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='feedback_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='feedback_relay',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='feedback_satisfied',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='feedback_study',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='feedback_think',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='movie_link_clicked',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='test_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_spent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
