# Generated by Django 3.2.4 on 2021-06-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210618_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='feedback_relay',
            new_name='feedback_rely',
        ),
        migrations.RemoveField(
            model_name='user',
            name='feedback_think',
        ),
        migrations.AddField(
            model_name='user',
            name='feedback_share',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='feedback_study',
            field=models.TextField(null=True),
        ),
    ]
