# Generated by Django 3.2.4 on 2021-06-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20210619_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('order_no', models.IntegerField()),
                ('movie_title', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('clicked', models.IntegerField()),
                ('timed', models.IntegerField()),
                ('rec_first_name', models.CharField(max_length=200)),
                ('rec_last_name', models.CharField(max_length=200)),
                ('rec_race', models.CharField(max_length=200)),
                ('rec_gender', models.CharField(max_length=6)),
                ('timestamp', models.DateTimeField()),
                ('readmore_count', models.IntegerField()),
            ],
        ),
    ]
