# Generated by Django 3.2.4 on 2021-06-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_user_user_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='movie_link_clicked',
            field=models.IntegerField(default=0),
        ),
    ]
