# Generated by Django 3.2.4 on 2021-07-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20210701_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('user_movies_pattern', models.CharField(max_length=500)),
                ('user_names_pattern', models.CharField(max_length=500)),
            ],
        ),
    ]
