# Generated by Django 3.2.4 on 2021-07-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20210717_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpattern',
            name='user_faces_pattern',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
