# Generated by Django 3.2.4 on 2021-07-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_userpattern_user_faces_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpattern',
            name='faces_index',
            field=models.IntegerField(default=0),
        ),
    ]
