# Generated by Django 3.2.4 on 2021-10-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20210729_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='movies_select_count_2',
            field=models.IntegerField(null=True),
        ),
    ]
