# Generated by Django 3.2.4 on 2021-11-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_auto_20211107_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='load_more_time_1',
            field=models.CharField(default='Load More', max_length=50),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='load_more_time_2',
            field=models.CharField(default='Load More', max_length=50),
        ),
    ]
